"""Справочник кодов событий «Орион»/«С2000-ПП». Названия взяты из РЭ; event_type — классификация только для UI."""
from __future__ import annotations

from dataclasses import dataclass

@dataclass(frozen=True)
class DefaultEventCode:
    label: str
    event_type: str
    priority: int | None = None

DEFAULT_EVENT_CODES: dict[int, DefaultEventCode] = {
    1: DefaultEventCode('Восстановление сети 220 В', 'normal', 150),
    2: DefaultEventCode('Авария сети 220 В', 'fault', 199),
    3: DefaultEventCode('Тревога проникновения', 'alarm', 238),
    4: DefaultEventCode('Помеха', 'attention', 222),
    5: DefaultEventCode('Отключение звука', 'attention', 132),
    6: DefaultEventCode('Помеха устранена', 'normal', 144),
    7: DefaultEventCode('Ручное включение исполнительного устройства', 'normal', 101),
    8: DefaultEventCode('Ручное выключение исполнительного устройства', 'normal', 100),
    9: DefaultEventCode('Активация УДП', 'alarm', 178),
    10: DefaultEventCode('Восстановление УДП', 'normal', 165),
    14: DefaultEventCode('Подбор кода', 'attention', 102),
    15: DefaultEventCode('Дверь открыта', 'attention', 175),
    17: DefaultEventCode('Неудачное взятие', 'fault', 204),
    18: DefaultEventCode('Предъявлен код принуждения', 'attention', 239),
    19: DefaultEventCode('Тест', 'info', 0),
    20: DefaultEventCode('Вход в режим тестирования', 'info', 106),
    21: DefaultEventCode('Выход из режима тестирования', 'info', 105),
    22: DefaultEventCode('Восстановление контроля', 'normal', 137),
    23: DefaultEventCode('Задержка взятия', 'info', 183),
    24: DefaultEventCode('Взятие входа на охрану', 'normal', 174),
    25: DefaultEventCode('Доступ закрыт', 'normal', 154),
    26: DefaultEventCode('Доступ отклонен', 'attention', 131),
    27: DefaultEventCode('Дверь взломана', 'alarm', 211),
    28: DefaultEventCode('Доступ предоставлен', 'normal', 25),
    29: DefaultEventCode('Запрет доступа', 'attention', 130),
    30: DefaultEventCode('Восстановление доступа', 'normal', 25),
    31: DefaultEventCode('Дверь закрыта', 'normal', 168),
    32: DefaultEventCode('Проход', 'info'),
    33: DefaultEventCode('Дверь заблокирована', 'attention', 210),
    34: DefaultEventCode('Идентификация', 'info', 127),
    35: DefaultEventCode('Восстановление технологического входа', 'normal', 162),
    36: DefaultEventCode('Нарушение технологического входа', 'fault', 163),
    37: DefaultEventCode('Пожар', 'alarm', 243),
    38: DefaultEventCode('Нарушение 2-го технологического входа', 'fault', 11),
    39: DefaultEventCode('Восстановление нормы оборудования', 'normal', 11),
    40: DefaultEventCode('Пожар 2', 'alarm', 244),
    41: DefaultEventCode('Неисправность оборудования', 'fault', 218),
    42: DefaultEventCode('Неизвестное устройство', 'fault', 103),
    43: DefaultEventCode('Предупреждение', 'attention', 241),
    44: DefaultEventCode('Внимание!', 'attention', 242),
    45: DefaultEventCode('Обрыв входа', 'fault', 221),
    46: DefaultEventCode('Обрыв ДПЛС', 'fault', 205),
    47: DefaultEventCode('Восстановление ДПЛС', 'normal', 147),
    48: DefaultEventCode('Сработка 2-го датчика', 'attention', 5),
    58: DefaultEventCode('Тихая тревога', 'alarm', 240),
    61: DefaultEventCode('Сброс конфигурации', 'attention', 92),
    62: DefaultEventCode('Изменение конфигурации', 'attention', 91),
    67: DefaultEventCode('Изменение даты', 'info', 126),
    69: DefaultEventCode('Журнал заполнен', 'attention', 125),
    70: DefaultEventCode('Журнал переполнен', 'fault', 124),
    71: DefaultEventCode('Понижение уровня', 'attention', 177),
    72: DefaultEventCode('Норма уровня', 'normal', 170),
    73: DefaultEventCode('Изменение времени', 'info', 123),
    74: DefaultEventCode('Повышение уровня', 'attention', 181),
    75: DefaultEventCode('Аварийное повышение уровня', 'alarm', 215),
    76: DefaultEventCode('Повышение температуры', 'attention', 180),
    77: DefaultEventCode('Аварийное понижение уровня', 'alarm', 214),
    78: DefaultEventCode('Температура в норме', 'normal', 169),
    79: DefaultEventCode('Тревога затопления', 'alarm', 236),
    80: DefaultEventCode('Восстановление датчика затопления', 'normal', 173),
    82: DefaultEventCode('Неисправность термометра', 'fault', 217),
    83: DefaultEventCode('Восстановление термометра', 'normal', 159),
    84: DefaultEventCode('Начало локального программирования', 'info', 122),
    109: DefaultEventCode('Снятие входа с охраны', 'disabled', 185),
    110: DefaultEventCode('Тревога сброшена', 'normal', 121),
    111: DefaultEventCode('Включение ШС', 'normal', 139),
    112: DefaultEventCode('Отключение ШС', 'disabled', 134),
    113: DefaultEventCode('Включение выхода', 'normal', 138),
    114: DefaultEventCode('Отключение выхода', 'disabled', 133),
    117: DefaultEventCode('Восстановление снятого входа', 'normal', 184),
    118: DefaultEventCode('Тревога входа', 'alarm', 237),
    119: DefaultEventCode('Нарушение снятого входа', 'fault', 186),
    121: DefaultEventCode('Обрыв выхода', 'fault', 213),
    122: DefaultEventCode('КЗ выхода', 'fault', 212),
    123: DefaultEventCode('Восстановление выхода', 'normal', 158),
    126: DefaultEventCode('Потеря связи с выходом', 'fault', 226),
    127: DefaultEventCode('Восстановление связи с выходом', 'normal', 142),
    128: DefaultEventCode('Изменение состояния выхода', 'info', 97),
    130: DefaultEventCode('Включение насоса', 'normal', 182),
    131: DefaultEventCode('Выключение насоса', 'normal', 172),
    135: DefaultEventCode('Ошибка при автоматическом тестировании', 'fault', 208),
    137: DefaultEventCode('Пуск', 'alarm', 250),
    138: DefaultEventCode('Неудачный пуск', 'fault', 231),
    139: DefaultEventCode('Неудачный пуск пожаротушения', 'fault', 245),
    140: DefaultEventCode('Тест', 'info', 120),
    141: DefaultEventCode('Задержка пуска АУП', 'info', 252),
    142: DefaultEventCode('Автоматика АУП выключена', 'disabled', 189),
    143: DefaultEventCode('Отмена пуска АУП', 'normal', 235),
    144: DefaultEventCode('Тушение', 'alarm', 255),
    145: DefaultEventCode('Аварийный пуск АУП', 'alarm', 254),
    146: DefaultEventCode('Пуск АУП', 'alarm', 253),
    147: DefaultEventCode('Блокировка пуска АУП', 'fault', 190),
    148: DefaultEventCode('Автоматика АУП включена', 'normal', 171),
    149: DefaultEventCode('Взлом корпуса прибора', 'alarm', 194),
    150: DefaultEventCode('Пуск речевого оповещения', 'alarm', 251),
    151: DefaultEventCode('Отмена пуска РО', 'normal', 234),
    152: DefaultEventCode('Восстановление корпуса прибора', 'normal', 146),
    153: DefaultEventCode('ИУ в рабочем состоянии', 'normal', 179),
    154: DefaultEventCode('ИУ в исходном состоянии', 'normal', 166),
    155: DefaultEventCode('Отказ ИУ', 'fault', 229),
    156: DefaultEventCode('Ошибка ИУ', 'fault', 223),
    157: DefaultEventCode('Сброс задержки', 'normal', 98),
    158: DefaultEventCode('Восстановление внутренней зоны', 'normal', 160),
    159: DefaultEventCode('Задержка пуска РО', 'info', 249),
    161: DefaultEventCode('Останов задержки пуска АУП', 'normal', 247),
    162: DefaultEventCode('Увеличение задержки пуска', 'info', 90),
    164: DefaultEventCode('Саботаж', 'alarm', 95),
    165: DefaultEventCode('Ошибка параметров входа', 'fault', 219),
    186: DefaultEventCode('Требуется замена батареи', 'fault', 193),
    187: DefaultEventCode('Потеря связи со входом', 'fault', 227),
    188: DefaultEventCode('Восстановление связи со входом', 'normal', 143),
    189: DefaultEventCode('Потеря связи по ДПЛС1', 'fault', 192),
    190: DefaultEventCode('Потеря связи по ДПЛС2', 'fault', 191),
    191: DefaultEventCode('Восстановление связи по ДПЛС1', 'normal', 136),
    192: DefaultEventCode('Отключение выходного напряжения', 'disabled', 203),
    193: DefaultEventCode('Подключение выходного напряжения', 'normal', 157),
    194: DefaultEventCode('Перегрузка источника питания', 'fault', 202),
    195: DefaultEventCode('Перегрузка источника питания устранена', 'normal', 156),
    196: DefaultEventCode('Неисправность зарядного устройства', 'fault', 201),
    197: DefaultEventCode('Восстановление зарядного устройства', 'normal', 155),
    198: DefaultEventCode('Неисправность источника питания', 'fault', 200),
    199: DefaultEventCode('Восстановление источника питания', 'normal', 152),
    200: DefaultEventCode('Восстановление батареи', 'normal', 149),
    201: DefaultEventCode('Восстановление связи по ДПЛС2', 'normal', 135),
    202: DefaultEventCode('Неисправность батареи', 'fault', 198),
    203: DefaultEventCode('Перезапуск прибора', 'info', 117),
    204: DefaultEventCode('Требуется обслуживание', 'attention', 216),
    205: DefaultEventCode('Ошибка теста АКБ', 'fault', 197),
    206: DefaultEventCode('Понижение температуры', 'attention', 176),
    211: DefaultEventCode('Батарея разряжена', 'fault', 196),
    212: DefaultEventCode('Разряд резервной батареи', 'fault', 195),
    213: DefaultEventCode('Восстановление резервной батареи', 'normal', 148),
    214: DefaultEventCode('Короткое замыкание входа', 'fault', 220),
    215: DefaultEventCode('Короткое замыкание ДПЛС', 'fault', 207),
    216: DefaultEventCode('Сработка датчика', 'alarm', 94),
    217: DefaultEventCode('Отключение ветви RS-485', 'fault', 145),
    218: DefaultEventCode('Восстановление ветви RS-485', 'normal', 116),
    220: DefaultEventCode('Срабатывание СДУ', 'alarm', 187),
    221: DefaultEventCode('Отказ СДУ', 'fault', 232),
    222: DefaultEventCode('Повышение напряжения ДПЛС', 'fault', 206),
    223: DefaultEventCode('Отметка наряда', 'info', 104),
    224: DefaultEventCode('Некорректный ответ устройства в ДПЛС', 'fault', 225),
    225: DefaultEventCode('Неустойчивый ответ устройства в ДПЛС', 'fault', 224),
    229: DefaultEventCode('Задержка пуска', 'info', 248),
    230: DefaultEventCode('Останов задержки пуска', 'normal', 246),
    231: DefaultEventCode('Остановка', 'normal', 233),
    232: DefaultEventCode('Увеличение задержки пуска', 'info', 88),
    233: DefaultEventCode('Сброс задержки пуска', 'normal', 89),
    237: DefaultEventCode('Раздел снят по принуждению', 'disabled', 113),
    241: DefaultEventCode('Раздел взят', 'normal', 115),
    242: DefaultEventCode('Раздел снят', 'disabled', 114),
    249: DefaultEventCode('Окончание локального программирования', 'info', 96),
    250: DefaultEventCode('Потеряна связь с прибором', 'fault', 228),
    251: DefaultEventCode('Восстановлена связь с прибором', 'normal', 141),
    252: DefaultEventCode('Подмена прибора', 'fault', 230),
    253: DefaultEventCode('Включение пульта С2000М', 'info', 110),
    254: DefaultEventCode('Прошел день – отметка времени', 'info', 109),
    255: DefaultEventCode('Прошел час – отметка времени', 'info', 108),
}

EVENT_TYPE_CHOICES = ("normal", "alarm", "attention", "fault", "disabled", "info", "unknown")
